# gsensor drivers

obj-$(CONFIG_PS_VL53L0X) 		+= ps_vl53l0x.o vl53l0x_api.o vl53l0x_api_calibration.o vl53l0x_api_core.o vl53l0x_api_ranging.o vl53l0x_api_strings.o vl53l0x_platform_log.o vl53l0x_platform.o

